en:
  languageName: English
  weight: 1
  ### copyright (markdown can be used) ###
  copyright: "Copyright &copy; {{< current_year >}} uOttawa Aeronautics Team. [Dot Org Theme](https://github.com/cncf/dot-org-hugo-theme) for Hugo by [CNCF](https://www.cncf.io)."
  title: "uOttawa Aeronautics Team"
  params:
    description: "Site Description"
    email: "aeronautics@uottawa.ca"
    address: "150 Louis-Pasteur Private, Ottawa, ON, K1N 9A7 üá®üá¶"

    ### calls to action ###
    main_cta:
      text: "Join"
      link: "/join/"
    footer_cta:
      text: "Join"
      link: "/join/"
    github_edit: "Edit this page on GitHub"
    land_acknowledgement: "UOAeronautics at the University of Ottawa acknowledges and respects the Omam√¨w√¨nini Anishn√†beg (Algonquin), the traditional guardians of this land. We recognize their longstanding relationship with this unceded territory and honor all Indigenous peoples who call Ottawa home. We acknowledge the traditional knowledge keepers, both young and old, and celebrate their contributions to science, technology, engineering, and mathematics. To learn more, [we invite you to read about the University of Ottawa's Indigenous information.](https://www.uottawa.ca/about-us/indigenous)"

  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "About"
      url: "/#"
      weight: 1
    - identifier: "our-mission"
      name: "Our Mission"
      url: "/mission/"
      weight: 1
      post: "Our team purpose."
      parent: "about"
    - identifier: "meet-the-team"
      name: "Meet The Team"
      url: "/the-team/"
      weight: 2
      post: "Learn more about who we are."
      parent: "about"
    
    - identifier: "competition"
      name: "Competition"
      url: "/competition/"
      weight: 3
      post: "See current and past aircraft."
    - identifier: "competition-about"
      name: "About the Competition"
      url: "/competition/"
      weight: 1
      post: "Learn more about the SAE Aero Design Competition"
      parent: "competition"
    - identifier: "micro-2026"
      name: "2026 Micro"
      url: "/competition/2026-micro"
      weight: 8
      parent: "competition"
    - identifier: "advanced-2026"
      name: "2026 Advanced"
      url: "/competition/2026-advanced"
      weight: 9
      parent: "competition"
    - identifier: "micro-2025"
      name: "2025 Micro"
      url: "/competition/2025-micro"
      weight: 10
      parent: "competition"
    - identifier: "advanced-2025"
      name: "2025 Advanced"
      url: "/competition/2025-advanced"
      weight: 11
      parent: "competition"


    - identifier: "contact"
      name: "Contact"
      url: "/contact/"
      weight: 2
      
    - identifier: "posts"
      name: "Posts"
      url: "/blog/"
      weight: 3

    - identifier: "sponsors"
      name: "Sponsors"
      url: "/#"
      weight: 4
    - identifier: "our-sponsors"
      name: "Our Sponsors"
      url: "/sponsors/"
      weight: 1
      post: "See our generous sponsors."
      parent: "sponsors"
    - identifier: "sponsor-us"
      name: "Sponsor Us"
      url: "/sponsor-us/"
      weight: 2
      post: "Become a sponsor."
      parent: "sponsors"
fr:
  languageName: Fran√ßais
  weight: 1
  contentDir: content/fr/
  ### copyright (markdown can be used) ###
  copyright: "Droits d'auteur &copy; {{< current_year >}} √âquipe d'a√©ronautique de l'uOttawa. [Th√®me Dot Org](https://github.com/cncf/dot-org-hugo-theme) pour Hugo par [CNCF](https://www.cncf.io)."
  title: "√âquipe a√©rospatiale de l'Universit√© d'Ottawa"
  email: aeronautics@uottawa.ca
  address: 150 Louis-Pasteur Private, Ottawa, ON, K1N 9A7 üá®üá¶
  params:
    description: "Site Description"

    ### calls to action ###
    main_cta:
      text: "Rejoignez-nous"
      link: "/rejoignez-nous/"
    footer_cta:
      text: "Rejoignez-nous"
      link: "/rejoignez-nous/"
    github_edit: "Edit this page on GitHub"
    land_acknowledgement: "UOAeronautics √† l'Universit√© d'Ottawa reconna√Æt et respecte les Omam√¨w√¨nini Anishn√†beg (Algonquins), gardiens traditionnels de ce territoire. Nous reconnaissons leur relation de longue date avec ce territoire non c√©d√© et rendons hommage √† tous les peuples autochtones qui consid√®rent Ottawa comme leur foyer. Nous rendons hommage aux gardiens du savoir traditionnel, jeunes et moins jeunes, et c√©l√©brons leur contribution aux sciences, √† la technologie, √† l'ing√©nierie et aux math√©matiques. Pour en savoir plus, [nous vous invitons √† consulter les informations sur les Autochtones de l'Universit√© d'Ottawa.](https://www.uottawa.ca/about-us/indigenous)"
  ### example menu showing children ###
  menu:
    main:
    - identifier: "about"
      name: "√Ä propos"
      url: "/#"
      weight: 1
    - identifier: "our-mission"
      name: "Notre mission"
      url: "/mission/"
      weight: 1
      post: "Notre objectif d'√©quipe."
      parent: "about"
    - identifier: "meet-the-team"
      name: "Rencontrer l'√©quipe"
      url: "/lequipe/"
      weight: 2
      post: "En savoir plus sur qui nous sommes."
      parent: "about"
    
    - identifier: "competition"
      name: "Concurrence"
      url: "/concours/"
      weight: 3
      post: "See current and past aircraft."
    - identifier: "competition-about"
      name: "√Ä propos de la concurrence"
      url: "/concours/"
      weight: 1
      post: "En savoir plus sur le concours SAE Aero Design"
      parent: "competition"
    - identifier: "micro-2025"
      name: "Micro 2025"
      url: "/concours/2025-micro"
      weight: 10
      parent: "competition"
    - identifier: "advanced-2025"
      name: "Avanc√©e 2025"
      url: "/concours/2025-avancee"
      weight: 11
      parent: "competition"


    - identifier: "contact"
      name: "Nous contacter"
      url: "/contact/"
      weight: 2

    - identifier: "sponsors"
      name: "Commanditaires"
      url: "/#"
      weight: 4
    - identifier: "our-sponsors"
      name: "Nos commanditaires"
      url: "/commanditaires/"
      weight: 1
      parent: "sponsors"
    - identifier: "sponsor-us"
      name: "Commanditez-nous"
      url: "/commanditez-nous/"
      weight: 2
      parent: "sponsors"

